- job:
    name: heat-dashboard-integration-tests
    parent: horizon-integration-tests
    required-projects:
      - name: openstack/horizon
      - name: openstack/heat
      - name: openstack/python-heatclient
      - name: openstack/heat-dashboard
    roles:
      - zuul: openstack-infra/devstack
      - zuul: openstack/horizon
    irrelevant-files:
      - ^.*\.rst$
      - ^doc/.*$
      - ^releasenotes/.*$
    vars:
      devstack_plugins:
        heat: https://opendev.org/openstack/heat
        heat-dashboard: https://opendev.org/openstack/heat-dashboard
      devstack_services:
        horizon: true
      tox_envlist: integration

- project:
    templates:
      - check-requirements
      - horizon-non-primary-django-jobs
      - horizon-nodejs14-jobs
      - openstack-lower-constraints-jobs
      - openstack-python3-xena-jobs-horizon
      - publish-openstack-docs-pti
      - release-notes-jobs-python3
    check:
      jobs:
        - heat-dashboard-integration-tests:
            voting: false
